export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const ADD_PROCUCT = 'ADD_PROCUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';